pluginManagement {
    repositories {
        def localMirror = System.getenv('DORAEMON_LOCAL_MAVEN')
        if (localMirror) maven { url uri(localMirror) }
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        def localMirror = System.getenv('DORAEMON_LOCAL_MAVEN')
        if (localMirror) maven { url uri(localMirror) }
        google()
        mavenCentral()
        jcenter()
        maven { url 'https://jitpack.io' }
        maven { url "https://s01.oss.sonatype.org/content/groups/public" }
    }
}

rootProject.name = "qian"
include ':app'
